In [2]:
import pyrootutils
root = pyrootutils.setup_root(
    search_from=".",
    indicator=".git",
    pythonpath=True,
    dotenv=True,
)

In [3]:
import anndata as ad
import scanpy as sc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
sciBPancreas = ad.read_h5ad(root / "data" / "sciBPancreas.h5ad")
sciBPancreas.obs

                tech celltype  size_factors
D101_5        celseq    gamma      0.028492
D101_43       celseq    gamma      0.079348
D101_93       celseq    gamma      0.037932
D102_4        celseq    gamma      0.047685
D172444_23    celseq    gamma      0.038683
...              ...      ...           ...
Sample_1594  smarter    gamma      1.000000
Sample_1595  smarter    gamma      1.000000
Sample_1597  smarter    gamma      1.000000
Sample_1598  smarter    gamma      1.000000
Sample_1600  smarter    gamma      1.000000

[16382 rows x 3 columns]

In [9]:
HVG_embryoatlas = ad.read_h5ad(root / "data" / "HVG_embryoatlas.h5ad")
HVG_embryoatlas.obs

,cell,barcode,sample,pool,stage,sequencing.batch,theiler,doub.density,doublet,cluster,cluster.sub,cluster.stage,cluster.theiler,stripped,celltype,colour,sizeFactor
cell_1,cell_1,AAAGGCCTCCACAA,1,1,E6.5,1,TS9,0.043114,False,2,4,2,3,False,Epiblast,635547,0.567139
cell_2,cell_2,AACAAACTCGCCTT,1,1,E6.5,1,TS9,1.129713,False,12,1,1,1,False,Primitive Streak,DABE99,1.178520
cell_5,cell_5,AACAGAGAATCAGC,1,1,E6.5,1,TS9,0.112121,False,3,7,4,6,False,ExE ectoderm,989898,0.891500
cell_6,cell_6,AACATATGAATCGC,1,1,E6.5,1,TS9,1.254709,False,1,1,3,7,False,Epiblast,635547,1.226646
cell_8,cell_8,AACCGATGGCTTCC,1,1,E6.5,1,TS9,1.345759,False,2,1,2,3,False,Epiblast,635547,1.381845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cell_139326,cell_139326,TTTCGAACGGTGAG,37,26,E8.5,3,TS12,0.476074,False,18,2,19,17,False,Erythroid3,EF4E22,1.189966
cell_139327,cell_139327,TTTCGAACTAACCG,37,26,E8.5,3,TS12,0.303505,False,18,2,19,17,False,Erythroid3,EF4E22,0.807176
cell_139329,cell_139329,TTTCTACTGGGATG,37,26,E8.5,3,TS12,0.344835,False,13,2,18,3,False,Somitic mesoderm,005579,1.186303
cell_139330,cell_139330,TTTCTACTTCTCTA,37,26,E8.5,3,TS12,0.497382,False,18,1,15,17,False,Erythroid3,EF4E22,1.474211
cell_139331,cell_139331,TTTGCATGCTGATG,37,26,E8.5,3,TS12,0.190718,False,10,5,10,20,False,Forebrain/Midbrain/Hindbrain,647a4f,1.108326

In [ ]:
Alles_filtered = ad.read_h5ad(root / "data" / "Alles_filtered.h5ad")
Alles_filtered.obs